<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Body OTP</name>
   <tag></tag>
   <elementGuidId>5fb48fbd-ef14-4b03-acb1-b8f2c4ebb37d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='html_msg_body']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#html_msg_body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>087e13f3-1953-424b-a1e0-aca190c25f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>843217b7-ba62-4b00-ae37-f848d899fb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML Email Message Body</value>
      <webElementGuid>54a4a01d-d86f-4c9f-99a0-801f66a95679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>92cf44d4-ddec-46ef-808e-33252a386c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7ddfbf5f-a8a8-4a17-a1c7-d438993c1630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>8f7570ff-b457-4797-9f11-a23ce1d37405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ed886ea-639a-4a75-9832-011de81bfb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    &lt;!-- HTML EMAIL BODY -->
                </value>
      <webElementGuid>80549250-70a3-49a0-ab1c-00ecea9c78f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html_msg_body&quot;)</value>
      <webElementGuid>de275f69-2584-4cee-8a73-afae18b094aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='html_msg_body']</value>
      <webElementGuid>3b99627c-bb76-46c5-82c5-d02d46db18d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-html']/iframe</value>
      <webElementGuid>e99b435a-79db-46e3-967b-394d363839d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTACHMENTS'])[1]/following::iframe[1]</value>
      <webElementGuid>aa81b7ac-6346-4311-91e5-22ee159d58bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINKS'])[1]/following::iframe[1]</value>
      <webElementGuid>b7f35b6e-2a4b-4576-94ff-453825025be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[no link text found]'])[1]/preceding::iframe[2]</value>
      <webElementGuid>d1c44323-ca5a-4e07-a25c-0c9a994a72d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.pinterest.com/sendgrid/'])[1]/preceding::iframe[2]</value>
      <webElementGuid>b9a8c69f-467e-4577-833a-75a619683c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;!-- HTML EMAIL BODY -->']/parent::*</value>
      <webElementGuid>0acb4229-7724-4ca9-824c-fca97a0bd5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bccb44b4-8fd6-4450-8f8f-04293bd142a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'html_msg_body' and @title = 'HTML Email Message Body' and @name = 'html_msg_body' and (text() = '
                    &lt;!-- HTML EMAIL BODY -->
                ' or . = '
                    &lt;!-- HTML EMAIL BODY -->
                ')]</value>
      <webElementGuid>f7692f19-1cfc-4b3c-b4cf-ac4833829fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
