<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Go</name>
   <tag></tag>
   <elementGuidId>e8557c4f-337e-4b68-af03-40cc9a46aa81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;subInbox($('#inbox_field').val());&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9697d1c8-ba28-4995-8018-b0756174e6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn</value>
      <webElementGuid>01d653d2-c963-4673-84e5-447133c4ad9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>subInbox($('#inbox_field').val());</value>
      <webElementGuid>c60965c1-ce3b-4579-be28-9a9118c7a585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            GO
        </value>
      <webElementGuid>324901cb-dd10-4386-b59f-d4eda2048474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox_pane&quot;)/div[1]/div[@class=&quot;wrapper-primary-input medium-w100&quot;]/button[@class=&quot;primary-btn&quot;]</value>
      <webElementGuid>effa2a82-d309-47b8-8c3b-0e51a73068ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;subInbox($('#inbox_field').val());&quot;]</value>
      <webElementGuid>99787c74-5bab-4d78-9461-3c308f1122d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox_pane']/div/div[5]/button</value>
      <webElementGuid>d292dc22-99ff-462c-8a58-b4c769f18548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Messages'])[1]/following::button[4]</value>
      <webElementGuid>5c4cfe56-de2f-4e87-bb36-be5a117e5df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Links Found'])[1]/following::button[4]</value>
      <webElementGuid>37898c7a-b24d-4ea6-b7e2-8d184702c7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[2]/preceding::button[1]</value>
      <webElementGuid>7e32c984-722c-49ec-8bf4-396995c489f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/preceding::button[1]</value>
      <webElementGuid>14756fec-c5a3-470e-b13a-80e76758456b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GO']/parent::*</value>
      <webElementGuid>5a54f9ba-3368-4de8-a9de-9c0b9da4ce0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>715b5432-2c74-4ccf-885d-83c098e3bc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            GO
        ' or . = '
            GO
        ')]</value>
      <webElementGuid>bab080ba-db2c-4d9d-aaf8-c6c7cc41dbe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
