<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Email</name>
   <tag></tag>
   <elementGuidId>e41b8fc3-563e-4a81-928d-ae2fc88165eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inbox_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inbox_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4aa49b1-ea49-4c81-a8a4-98e6306bb5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-input</value>
      <webElementGuid>a8b31a9e-8ace-4753-8096-1b7e4dbcc0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inbox_field</value>
      <webElementGuid>c9199cb4-5bfa-42fc-9b97-7ef239259800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>inbox field</value>
      <webElementGuid>eb3a4b44-bb96-470d-9775-ebaa1f0e8e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { subInbox($('#inbox_field').val()); return false; }</value>
      <webElementGuid>41d00b78-e403-432d-b85f-85193a677d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Use ANY Inbox you want @mailinator.com !</value>
      <webElementGuid>d1cbb296-c388-42e2-9685-43c5ed4aae7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox_field&quot;)</value>
      <webElementGuid>1578546d-dad3-45eb-9f18-19f05076f3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inbox_field']</value>
      <webElementGuid>00cbc110-a65f-4215-b65e-4cc46383c9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox_pane']/div/div[5]/input</value>
      <webElementGuid>239e1383-881a-4c8b-8a56-1814f8483ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>27182abf-7d28-4bce-a97f-eb8aada86791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inbox_field' and @title = 'Use ANY Inbox you want @mailinator.com !']</value>
      <webElementGuid>18824019-c8b1-4e28-b6ec-dd6d0f654432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
