<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OTP</name>
   <tag></tag>
   <elementGuidId>b6f27968-65bd-41ba-8de5-2f55778cffcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/center[@class=&quot;wrapper&quot;]/div[@class=&quot;webkit&quot;]/table[@class=&quot;wrapper&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;outer&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[5]/tbody[1]/tr[1]/td[1]/table[@class=&quot;column column-0&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;module&quot;]/tbody[1]/tr[1]/td[@class=&quot;outer-td&quot;]/table[@class=&quot;wrapper-mobile&quot;]/tbody[1]/tr[1]/td[@class=&quot;inner-td&quot;]/a[1][count(. | //*[@ref_element = 'Object Repository/Page_Mailinator/iframe_-- HTML EMAIL BODY --']) = count(//*[@ref_element = 'Object Repository/Page_Mailinator/iframe_-- HTML EMAIL BODY --'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'394062')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b236fc54-0e97-4311-9c8d-ac7b8d198065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
      <webElementGuid>cc6cef64-7f51-462d-b34f-1c540b85ed5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>14ecdba3-10bc-41d4-af38-ca4c53eb5bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>394062</value>
      <webElementGuid>6379a378-72e5-497a-a04a-833739e93f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[@class=&quot;wrapper&quot;]/div[@class=&quot;webkit&quot;]/table[@class=&quot;wrapper&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;outer&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[5]/tbody[1]/tr[1]/td[1]/table[@class=&quot;column column-0&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;module&quot;]/tbody[1]/tr[1]/td[@class=&quot;outer-td&quot;]/table[@class=&quot;wrapper-mobile&quot;]/tbody[1]/tr[1]/td[@class=&quot;inner-td&quot;]/a[1]</value>
      <webElementGuid>33c93749-dbf6-4c51-82c8-985c0de09710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Mailinator/Page_Mailinator/Body OTP</value>
      <webElementGuid>4b884226-5a1e-4e3a-8737-af00879f2ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'394062')]</value>
      <webElementGuid>e5010673-c2ef-4dd9-88b9-a13230efc6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode OTP Anda'])[1]/following::a[1]</value>
      <webElementGuid>874dadc6-c4f5-46c2-bad0-3e78f09bc0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang di Kino Siap'])[1]/following::a[1]</value>
      <webElementGuid>7aaefe38-1009-40f1-8301-d9e2236d55d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsubscribe'])[1]/preceding::a[6]</value>
      <webElementGuid>26b33aa2-c141-42d5-a663-373966919143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='394062']/parent::*</value>
      <webElementGuid>97bda6b6-9e6a-40c5-bc21-9a63ee6f7d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '')]</value>
      <webElementGuid>207f10e7-6b05-4d38-a59d-5a79447a8a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>5694883e-f1b8-4977-972f-a59d7a2eb09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '394062' or . = '394062')]</value>
      <webElementGuid>999b4ad8-f9f0-4f20-bd18-f6a7292fa483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
