<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11 Tidak Punya Toko Offline</name>
   <tag></tag>
   <elementGuidId>8cd8b2db-0c59-4090-a640-2efc58a9bde0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='false']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-radio.ant-radio-checked > input.ant-radio-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab9d03e1-afa5-4d7c-b1ca-c45cd59d3dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d0e81945-678e-4189-b814-904d88f77834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-radio-input</value>
      <webElementGuid>98d6ee06-243b-44d9-80fa-50b14ba1cc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a884f30-d2e2-4ac4-a1b4-b3e7627c1ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;have_store&quot;)/label[@class=&quot;ant-radio-wrapper ant-radio-wrapper-checked&quot;]/span[@class=&quot;ant-radio ant-radio-checked&quot;]/input[@class=&quot;ant-radio-input&quot;]</value>
      <webElementGuid>2ba2e786-360e-40e6-8d7e-94baffb2c14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='false']</value>
      <webElementGuid>ca2ff457-b355-42ec-a60b-ef933dcaa724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='have_store']/label[2]/span/input</value>
      <webElementGuid>1dfc7293-24b0-4c0c-9be3-cd48f8af86b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/input</value>
      <webElementGuid>8badcf02-c51b-4d58-b88c-078549b5a01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>8e7d2499-181c-44b1-ad3a-2a7abe00877d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
