<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12 Input Toko Online</name>
   <tag></tag>
   <elementGuidId>3066bfde-81ed-41f5-9a63-bbc0c179c9be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_online_store']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_online_store</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a1c99f2-bc68-49b7-86f2-6c951da14c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan url toko anda</value>
      <webElementGuid>9987dbc9-23b9-4cc1-90a0-8e69dbed1c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e03665-6843-4aba-90eb-40a0e0203532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__meta</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a12bed0c-7b21-47ff-aa10-ebb6b89b1d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d134502b-703e-49cc-92d2-45ab701e75e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_online_store</value>
      <webElementGuid>1e340494-c85f-4f0f-8d07-2264f0dddbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-store ant-input</value>
      <webElementGuid>57cd19cd-3e1e-44fc-abd6-b4b7b22c8355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_online_store&quot;)</value>
      <webElementGuid>918d655d-4df3-4c0f-a51b-20c8244c2d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_online_store']</value>
      <webElementGuid>98961325-e983-4df9-914b-af929f489c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputStore']/div/div/div/div/span/input</value>
      <webElementGuid>b577afef-dcbe-49a2-a2d5-a8d9b0bb47a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>939b8b8e-fb8e-4273-a6f5-ea30ae405981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukan url toko anda' and @type = 'text' and @id = 'input_online_store']</value>
      <webElementGuid>3cf98766-38cf-4481-9a80-2c4d231bcb77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
