<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12 Tidak Toko Online</name>
   <tag></tag>
   <elementGuidId>eafcec8a-ed9d-41e0-8012-9aa9bff27f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='false'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#have_online_store > label.ant-radio-wrapper.ant-radio-wrapper-checked > span.ant-radio.ant-radio-checked > input.ant-radio-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb242a44-835e-4e56-a49d-2c98582089ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da204105-84a3-4cd2-8a11-c13ef7c4fc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-radio-input</value>
      <webElementGuid>96382a8c-2cb6-48f7-b868-d6bc76e6e609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d098b1c-3974-459c-a269-43841aad581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;have_online_store&quot;)/label[@class=&quot;ant-radio-wrapper ant-radio-wrapper-checked&quot;]/span[@class=&quot;ant-radio ant-radio-checked&quot;]/input[@class=&quot;ant-radio-input&quot;]</value>
      <webElementGuid>e1adc06e-fbd1-49ab-bc68-67892ae532c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='false'])[2]</value>
      <webElementGuid>b94a01fe-d8cc-4b9e-b2f1-ecd976b4fec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='have_online_store']/label[2]/span/input</value>
      <webElementGuid>ae5b9793-343f-4cbe-972b-f11912df7a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/span/div/label[2]/span/input</value>
      <webElementGuid>8a8b9f61-417e-4a70-bebe-1353a0d9b09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>08217c9f-bd4f-4a59-a07f-7da840035cd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
