<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12 Ya Toko Online</name>
   <tag></tag>
   <elementGuidId>b4410e98-ff9c-43b8-9350-e6bb56915713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='true'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#have_online_store > label.ant-radio-wrapper.ant-radio-wrapper-checked > span.ant-radio.ant-radio-checked > input.ant-radio-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02307c65-d9ec-4bf7-8707-f132aab4e966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>25e5fc8d-44d6-4a89-95e4-d84ac9b39a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-radio-input</value>
      <webElementGuid>1d25b2d8-eedd-43cb-bbe5-2d718346aa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a62b4dfd-93ff-4b19-afac-5f256744866f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;have_online_store&quot;)/label[@class=&quot;ant-radio-wrapper ant-radio-wrapper-checked&quot;]/span[@class=&quot;ant-radio ant-radio-checked&quot;]/input[@class=&quot;ant-radio-input&quot;]</value>
      <webElementGuid>2e4c25c6-04a8-436d-a559-ad0380fc32d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='true'])[2]</value>
      <webElementGuid>ce1fb249-2420-4a83-8e45-6b0786fdfd6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='have_online_store']/label/span/input</value>
      <webElementGuid>faab9d42-4095-49af-a1e8-d4eadbf1d191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/span/div/label/span/input</value>
      <webElementGuid>956389a9-0f52-47dc-a485-9c63b47f4eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>c5397764-788f-4f16-8dfe-d776afca54e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
