<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7.2 Input Kelurahan</name>
   <tag></tag>
   <elementGuidId>8bc93fa9-d970-4264-b830-1d12dbc674b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user_area']/div/div/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_area > div.ant-select-selection.ant-select-selection--single > div.ant-select-selection__rendered > div.ant-select-search.ant-select-search--inline > div.ant-select-search__field__wrap > input.ant-select-search__field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b5f223a-8f17-44c5-a16b-db4f7fef34d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b1e0a09-5bd5-4b4e-96ac-0659024669e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>c4376d68-142c-4fee-9dae-e369d66af36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-search__field</value>
      <webElementGuid>3338bd87-fcd1-455c-940a-6be24380c5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_area&quot;)/div[@class=&quot;ant-select-selection ant-select-selection--single&quot;]/div[@class=&quot;ant-select-selection__rendered&quot;]/div[@class=&quot;ant-select-search ant-select-search--inline&quot;]/div[@class=&quot;ant-select-search__field__wrap&quot;]/input[@class=&quot;ant-select-search__field&quot;]</value>
      <webElementGuid>15840793-026f-4436-aefa-fb84694fdfb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='l']</value>
      <webElementGuid>5249553d-3201-4d63-89da-c125dc0c79a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user_area']/div/div/div[2]/div/input</value>
      <webElementGuid>261fcf84-56d4-477b-950e-44d63a8b6e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>56766ef9-1a4e-4d7f-a82d-e6c685a2a5ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
