<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu Profile</name>
   <tag></tag>
   <elementGuidId>fc5f2a3e-a9d7-4513-8903-45c73655e9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[3]/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.index_title_qMZXO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f387021-9ef4-4081-9a0f-2ae9fe7bc479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>index_title_qMZXO</value>
      <webElementGuid>ec8bb687-2c21-485f-a70f-9ba865f16128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>8df40131-43ab-47d3-96ae-975cb606dace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;index_navbar_gl0OH&quot;]/div[@class=&quot;cui__utils__content index_menu_23IrC&quot;]/div[@class=&quot;index_navigation_3upFP&quot;]/div[@class=&quot;index_dropdown_3Vjvq ant-dropdown-trigger ant-dropdown-open&quot;]/div[@class=&quot;index_title_qMZXO&quot;]</value>
      <webElementGuid>86936d37-be09-47a5-a756-f425210d363e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[3]/div[4]/div[2]</value>
      <webElementGuid>fbb99f24-49db-4d49-bf36-aaf0e4fb8378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::div[3]</value>
      <webElementGuid>81e841e6-f21b-46e4-9fbd-e011d722d1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kino Coin'])[1]/following::div[6]</value>
      <webElementGuid>7770a6fa-9ac2-45e8-8d80-1bc8591c2e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total poin yang Anda miliki'])[1]/preceding::div[1]</value>
      <webElementGuid>556c812e-1ed2-4ad9-b68e-96fba8cbfe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[1]/preceding::div[1]</value>
      <webElementGuid>8c462975-d2d0-4e0f-afab-9e058dea4b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile']/parent::*</value>
      <webElementGuid>670c0266-7833-4441-9e41-376e23644939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>934830b7-332d-420f-98fb-4acb35474502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>80762a47-ff66-4202-85bd-6b9c5ae92614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
